name: Update From Package
on:
  push:
    branches:
      - main

jobs:
  tag_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: salsify/action-detect-and-tag-new-version@v2
        id: version
        with:
          version-command: |
            git config user.name  "${{github.actor}}"
            git config user.email "${{github.actor}}@users.noreply.github.com"
            node update-tags.mjs
            git commit -q -a -m "Set id and schema paths for new version"

      - name: Publish Release
        uses: ghalactic/github-release-from-tag@v4
