name: Validate schema

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Run Prettier code style checks
      run: npx prettier -c .
