name: Validate schema

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: intelligence-ai/jsonschema@v0.2.0
      - run: jsonschema lint gcn --extension .schema.json --verbose
      - run: jsonschema fmt gcn --extension .schema.json --check --verbose
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: NPM Install
        run: npm ci
      - name: Validate
        run: npm run validate
